(function ensightenInit(){var ensightenOptions = {client: "npg", clientId: 322, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/npg/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/npg/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Thu May 21 11:18:34 GMT 2015", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),g;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof d)for(g in d){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+g;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+
encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=
0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=
a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=
function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};
b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};
b.bindDependencyDOMLoaded=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=
[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,g=b.dataDefinitionIds.length,f=0;f<g;f++)if(b.dataDefinitionIds[f]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=
null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=
function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,
50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};
var q=function(){var a=[],b=!1,c=!1;return{add:function(f){b&&!c?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){c=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=
log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",
b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=
-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},m="",n=f.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(f.navigationStart),b;for(b in c)void 0!==f[b]?(p=f[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";m=f.indexOf(".com/");n=f.indexOf("/code/");f=f.substring(m+4,n)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
	
if (!window[ensightenOptions.ns].data) {
	/*
 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={});
(function(){function c(a){return 10>a?"0"+a:a}function m(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var d=f[a];return"string"===typeof d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(f,c){var b,k,r,e,g=h,t,p=c[f];p&&"object"===typeof p&&"function"===typeof p.toJSON&&(p=p.toJSON(f));"function"===typeof d&&(p=d.call(c,f,p));switch(typeof p){case "string":return m(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";h+=a;t=[];if("[object Array]"===Object.prototype.toString.apply(p)){e=p.length;for(b=0;b<e;b+=1)t[b]=l(b,p)||"null";r=0===t.length?"[]":h?"[\n"+h+t.join(",\n"+h)+"\n"+g+"]":"["+t.join(",")+"]";h=g;return r}if(d&&"object"===typeof d)for(e=d.length,b=0;b<e;b+=1)"string"===typeof d[b]&&(k=d[b],(r=l(k,p))&&t.push(m(k)+(h?": ":":")+r));else for(k in p)Object.prototype.hasOwnProperty.call(p,k)&&(r=l(k,p))&&t.push(m(k)+(h?": ":":")+r);r=0===t.length?"{}":h?"{\n"+h+t.join(",\n"+
h)+"\n"+g+"}":"{"+t.join(",")+"}";h=g;return r}}var b=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=
/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h,a,f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},d;"function"!==typeof b.stringify&&(b.stringify=function(b,f,c){var k;a=h="";if("number"===typeof c)for(k=0;k<c;k+=1)a+=" ";else"string"===typeof c&&(a=c);if((d=f)&&"function"!==typeof f&&
("object"!==typeof f||"number"!==typeof f.length))throw Error("JSON.stringify");return l("",{"":b})});"function"!==typeof b.parse&&(b.parse=function(a,f){function d(a,b){var c,k,e=a[b];if(e&&"object"===typeof e)for(c in e)Object.prototype.hasOwnProperty.call(e,c)&&(k=d(e,c),void 0!==k?e[c]=k:delete e[c]);return f.call(a,b,e)}var b;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),"function"===typeof f?d({"":b},""):b;throw new SyntaxError("JSON.parse");})})();
window[ensightenOptions.ns].when=function(){function c(a,b,f,d){return l(a).then(b,f,d)}function m(a){this.then=a}function l(a){return b(function(b){b(a)})}function b(d){function c(a){n&&(u=e(a),f(n,u),n=v)}function k(a){c(h(a))}function r(b){n&&f(n,a(b))}var u,n=[];try{d(c,k,r)}catch(g){k(g)}return new m(function(a,d,f){return b(function(b,c,k){n?n.push(function(e){e.then(a,d,f).then(b,c,k)}):q(function(){u.then(a,d,f).then(b,c,k)})})})}function e(a){return a instanceof m?a:a!==Object(a)?g(a):b(function(b,
d,f){q(function(){try{var c=a.then;"function"===typeof c?B(c,a,b,d,f):b(g(a))}catch(k){d(k)}})})}function g(a){var b=new m(function(d){try{return"function"==typeof d?e(d(a)):b}catch(f){return h(f)}});return b}function h(a){var b=new m(function(d,f){try{return"function"==typeof f?e(f(a)):b}catch(c){return h(c)}});return b}function a(b){var d=new m(function(f,c,k){try{return"function"==typeof k?a(k(b)):d}catch(e){return a(e)}});return d}function f(a,b){q(function(){for(var d,f=0;d=a[f++];)d(b)})}function d(a,
d,f,k,e){r(2,arguments);return c(a,function(a){return b(function(b,f,k){function e(a){l(a)}function r(a){q(a)}var n,g,w,h,q,l,x,z;x=a.length>>>0;n=Math.max(0,Math.min(d,x));w=[];g=x-n+1;h=[];if(n)for(l=function(a){h.push(a);--g||(q=l=u,f(h))},q=function(a){w.push(a);--n||(q=l=u,b(w))},z=0;z<x;++z)z in a&&c(a[z],r,e,k);else b(w)}).then(f,k,e)})}function n(a,b,d,f){r(1,arguments);return w(a,x).then(b,d,f)}function w(a,d){return c(a,function(a){return b(function(b,f,k){var e,r,n,u,g;n=r=a.length>>>0;
e=[];if(n)for(u=function(a,r){c(a,d).then(function(a){e[r]=a;--n||b(e)},f,k)},g=0;g<r;g++)g in a?u(a[g],g):--n;else b(e)})})}function q(a){1===A.push(a)&&D(k)}function k(){for(var a,b=0;a=A[b++];)a();A=[]}function r(a,b){for(var d,f=b.length;f>a;)if(d=b[--f],null!=d&&"function"!=typeof d)throw Error("arg "+f+" must be a function");}function u(){}function x(a){return a}c.defer=function(){var a,d,f;a={promise:v,resolve:v,reject:v,notify:v,resolver:{resolve:v,reject:v,notify:v}};a.promise=d=b(function(b,
c,k){a.resolve=a.resolver.resolve=function(a){if(f)return l(a);f=!0;b(a);return d};a.reject=a.resolver.reject=function(a){if(f)return l(h(a));f=!0;c(a);return d};a.notify=a.resolver.notify=function(a){k(a);return a}});return a};c.resolve=l;c.reject=function(a){return c(a,h)};c.join=function(){return w(arguments,x)};c.all=n;c.map=w;c.reduce=function(a,b){var d=B(p,arguments,1);return c(a,function(a){var f;f=a.length;d[0]=function(a,d,k){return c(a,function(a){return c(d,function(d){return b(a,d,k,
f)})})};return t.apply(a,d)})};c.any=function(a,b,f,c){return d(a,1,function(a){return b?b(a[0]):a[0]},f,c)};c.some=d;c.isPromise=function(a){return a&&"function"===typeof a.then};m.prototype={otherwise:function(a){return this.then(v,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return n(b,function(b){return a.apply(v,b)})})},always:function(a,b){return this.then(a,
a,b)}};var t,p,B,D,A,E,y,C,v;A=[];E=setTimeout;D="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){E(a,0)};y=Function.prototype;C=y.call;B=y.bind?C.bind(C):function(a,b){return a.apply(b,p.call(arguments,2))};y=[];p=y.slice;t=y.reduce||function(a){var b,d,f,c;c=0;b=Object(this);f=b.length>>>0;d=arguments;if(1>=d.length)for(;;){if(c in b){d=b[c++];break}if(++c>=f)throw new TypeError;
}else d=d[1];for(;c<f;++c)c in b&&(d=a(d,b[c],c,b));return d};return c}();
(function(){function c(b,c){return l.all(c||[],function(c){return b.apply(null,c)})}function m(e){var g=b.call(arguments,1);return function(){return c(e,g.concat(b.call(arguments)))}}var l,b;l=window[ensightenOptions.ns].when;b=[].slice;l.apply=c;l.call=function(e){return c(e,b.call(arguments,1))};l.lift=m;l.bind=m;l.compose=function(e){var g=b.call(arguments,1);return function(){var h=b.call(arguments),h=c(e,h);return l.reduce(g,function(a,b){return b(a)},h)}}})();
window[ensightenOptions.ns].data=function(c,m){function l(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var b={engines:{memory:{get:function(a){if(e.utils.isArray(a)){for(var f=[],d=0;d<a.length;d++)f.push(b.data[a[d]]);return c[ensightenOptions.ns].when.resolve(f)}f=b.dataDefinitions[a]||{storage:{get:function(){}}};f=f.storage.get(f);b.data[a]=f;return c[ensightenOptions.ns].when.resolve(b.data[a])},set:function(a,f){if(e.utils.isArray(a))for(var d in a)b.data[a[d]]=
f[d];else b.data[a]=f;return c[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(e.utils.isArray(a))for(var f in a)delete b.data[a[f]];else delete b.data[a];return c[ensightenOptions.ns].when.resolve(!0)},clear:function(a){b.data={};b.definitions={};return c[ensightenOptions.ns].when.resolve(!0)},all:function(){return c[ensightenOptions.ns].when.resolve(b.data)}}},normalizeInputArgs:function(a,b){var d={key:[],val:m},c;if(e.utils.isPlainObject(a))for(c in d.val=[],a)d.key.push(c),d.val.push(a[c]);
else e.utils.isArray(a),d.key=a,d.val=b;return d},definitions:{},data:{}},e={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},g=function(){return c[ensightenOptions.ns].when.reject("Not Implemented.")};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=
l;b.DataDefinitionException=l;b.checkForInvalidDataDefinitions=function(a){e.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a)),!0):!1};b.collectAvailableDataDefinitions=function(a){for(var f=[],d=0;d<a.length;d++){var n=parseInt(a[d],10),g=c[ensightenOptions.ns].dataDefinitions[n];if(null===g||g===m)if(g=e.storage.session.get({id:n}),null!==g&&g!==m)e.set(n,g),b.dataDefinitions[n]={id:n,
load:"visitor",storage:e.storage.visitor,missingDDFromCache:!0},f.push(c[ensightenOptions.ns].data.get(""+n));else return c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Invalid data definition used: "+n)),{promises:[],isInvalid:!0};else f.push(c[ensightenOptions.ns].data.get(a[d]))}return{promises:f,isInvalid:!1}};b.getSync=function(a){function f(a){var b=a.extract||n,f=a.transform||g,c=!1,k=null,e=null;try{k=b()}catch(q){k=null,c=!0}try{e=f(k)}catch(h){e=null,c=!0}c&&d.push(a.id);
return e}var d=[],n=function(){return document},g=function(a){return null!==a&&a!==m?a.toString():null},q=parseInt(a);a="string"===typeof a?a.split("."):[];var k="";isNaN(q)?3==a.length&&(k=f(e.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2]))):k=f(e.getDataDefinitionById(q));0<d.length&&c[ensightenOptions.ns].reportException(new b.DataDefinitionException(d,"Error resolving data definitions synchronously: "+d));return k};b.dataDefinitions={};b.dataDefinitionsBySourceCollName={};e.defineEngine=
function(a,f){var d,e=["get","set","remove","clear","all"];b.engines[a]=f;if(!f.returnsPromise)for(d=0;d<e.length;d++){var g=e[d];f[g]=c[ensightenOptions.ns].when.lift(f[g])}};e.storage={instance:{set:function(a,b){},get:function(a){return b.getSync(a.id)}},page:{set:function(a,b){},get:function(a){return b.data[a.id]}},session:{set:function(a,b){var d=e.storage.session.get({id:a}),g=new Date,h=g.getTime();g.setTime(h+18E5);null!=d&&(b=d);c[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:g.toGMTString()});
d={expires:g.getTime(),value:b};c[ensightenOptions.ns].data.local.utils.set(a,d)},get:function(a){var b=c[ensightenOptions.ns].data.cookie.utils.get(a.id),d=c.JSON&&c.JSON.stringify?c.JSON:c[ensightenOptions.ns].JSON,d=d||{},e,g=new Date,g=g.getTime();if(null===b){try{e=d.parse(c[ensightenOptions.ns].data.local.utils.get(a.id))}catch(h){e=null}null!=e&&(e.expires=+e.expires,g<=e.expires?b=e.value:""==e.expires&&e.value!=m?b=e.value:c[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},
visitor:{set:function(a,b){var d=e.storage.session.get({id:a});null!=d&&(b=d);c[ensightenOptions.ns].data.cookie.utils.set(a,b);c[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return e.storage.session.get(a)}}};e.getEngine=e.engine=function(a){return a?b.engines[a]||{get:g,set:g,remove:g,clear:g,all:g}:b.engines};e.all=function(a){return c[ensightenOptions.ns].data.engine(a||"memory").all()};e.get=function(a,f,d){f=f||"memory";d=d||{};-1<a.indexOf(",")&&(a=a.split(","));
a=b.normalizeInputArgs(a);return d.wait?b.getWait(a.key,c[ensightenOptions.ns].data.engine(f),d):b.data&&b.data.hasOwnProperty(a.key)?c[ensightenOptions.ns].data.engine(f).get(a.key):b.getWaitForKey(a.key,c[ensightenOptions.ns].data.engine(f),d)};b.getWait=function(a,b,d){var g=+new Date,h=c[ensightenOptions.ns].when.defer(),q=function(){var c=b.get(a);if(-1===d.wait)return c;c.then(function(a){d.setCheck(a)?h.resolve(a):setTimeout(k,d.interval)},function(a){setTimeout(k,d.interval)})},k=function(){var a=
+new Date-g;-1!==d.wait&&a<d.wait?q():h.reject("Timeout")};d.interval=d.interval||500;d.wait=d.wait||5E3;e.utils.isArray(a)?d.setCheck=d.setCheck||function(a){for(var b=!0,d=0;d<a.length;d++)b=b&&!!a[d];return b}:d.setCheck=d.setCheck||function(a){return!!a};q();return h.promise};b.getWaitForKey=function(a,f,d){var e=c[ensightenOptions.ns].when.defer(),g=function(){if(b.data&&b.data.hasOwnProperty(a)){var c=f.get(a);if(-1===d.wait)return c;c.then(function(a){e.resolve(a)},function(a){e.reject(a)})}else setTimeout(h,
d.interval)},h=function(){g()};d.interval=d.interval||100;d.wait=d.wait||1;g();return e.promise};e.set=function(a,f,d){var e=b.normalizeInputArgs(a,f);Array.prototype.slice.call(arguments);return c[ensightenOptions.ns].data.engine(d||"memory").set(e.key,e.val)};e.remove=function(a,b){return c[ensightenOptions.ns].data.engine(b||"memory").remove(a)};e.clear=function(a){return c[ensightenOptions.ns].data.engine(a||"memory").clear()};e.define=function(a,f){f&&(a.name=f.id||f.name);if(!a.name)return c[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));
a.id=a.name;var d=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return c[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=c[ensightenOptions.ns].data.engine("memory");a.storage=e.storage[d.toLowerCase()]||e.storage.page;var g=a.extract||function(){return document},h=a.transform||function(a){return a},q=function(b,d){var e=[];e.push(a.persist.set(b,
d));a.storage.set(a.id,d);"object"==typeof c[ensightenOptions.ns].data.dataExport&&c[ensightenOptions.ns].data.dataExport(b,d,a.collection);c[ensightenOptions.ns].when.all(e).then(function(a){k.resolve(a)},function(a){k.reject(a)})},k=c[ensightenOptions.ns].when.defer();a.trigger().then(function(){k.resolve(c[ensightenOptions.ns].when.reduce([g(),h,q],function(b,d,c,e){if(1==c)return d(b);2==c&&d(a.name,b)}))},function(a){k.reject(a)});b.dataDefinitions[a.id]=a;b.dataDefinitionsBySourceCollName[""+
a.source+"."+a.collection+"."+a.dataDefName]=a;return k.promise};e.checkConditions=function(a){var f,d={lt:function(a,d){var e=+a,f=+d;return isNaN(e)||isNaN(f)?(c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+d)),!1):e<f},gt:function(a,d){var e=+a,f=+d;return isNaN(e)||isNaN(f)?(c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
a+", compareTo: "+d)),!1):e>f},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==m||""==a?!1:!0},re:function(a,b,d){b=new RegExp(b,d?"i":"");try{return a.match(b)}catch(c){return!1}},starts:function(a,b,c){b=e.utils.escapeRegEx(b);return d.re(a,"^"+b,c)},ends:function(a,b,c){b=e.utils.escapeRegEx(b);return d.re(a,b+"$",c)},contains:function(a,b,c){b=e.utils.escapeRegEx(b);return d.re(a,".*"+b+".*",c)}};d.is=d.eql;d["starts with"]=d.starts;d["ends with"]=d.ends;d["is greater than"]=
d.gt;d["is less than"]=d.lt;d.matches=d.re;for(f=0;f<a.values.length;f++){var g=(a.customComparator?a.customComparator[f]?a.customComparator[f]:d[a.comparators[f]]:d[a.comparators[f]])(a.values[f],a.compareTo[f],a.caseInsensitive?a.caseInsensitive[f]||!1:!1);a.not[f]&&(g=!g);if(!g)return!1}return!0};e.triggerPromise=function(a,b,d){d=d||5E3;var e=+new Date,g=c[ensightenOptions.ns].when.defer();(function(){var c=a();c!=b?g.resolve(c):+new Date-e<d?setTimeout(arguments.callee,200):g.reject("timed out")})();
return g.promise};e.timeoutPromise=function(a,b){var d=c[ensightenOptions.ns].when.defer();b=b||800;a.then(d.resolve,d.reject);setTimeout(function(){d.reject(Error("timed out"))},b);return d.promise};e.delayTrigger=function(a){a=a||10;var b=c[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};e.delayUntilTrigger=function(a,b,d,e){d=d||null;e=e||200;var g=+new Date,h=c[ensightenOptions.ns].when.defer();(function(){var c=a();c!=b?h.resolve(c):d?+new Date-g<d?setTimeout(arguments.callee,
e):h.reject("timed out"):setTimeout(arguments.callee,e)})();return h.promise};b.applyTrigger=function(a){var b=c[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};e.bottomOfBodyTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindDOMParsed)};e.afterEnsightenCompleteTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindPageSpecificCompletion)};e.afterElementsDownloadedTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindDOMLoaded)};
e.getAllDataDefinitionsOnCurrentPage=function(){return b.dataDefinitions};e.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return b.dataDefinitionsBySourceCollName};e.getDataDefinitionById=function(a){return b.dataDefinitions[a||-1]||{}};e.getDataDefinitionBySourceCollectionName=function(a,c,d){return b.dataDefinitionsBySourceCollName[""+a+"."+c+"."+d]||{}};e.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:b.dataDefinitions[a[1]]||{}};e.resolve=function(a,
f){var d=this,g=null;if(!b.checkForInvalidDataDefinitions(a))if(f)c[ensightenOptions.ns].bindDataDefinitionComplete(function(){var e=b.collectAvailableDataDefinitions(a);e.isInvalid||c[ensightenOptions.ns].when.all(e.promises).then(function(e){try{f.apply(d,e)}catch(k){c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+k))}},function(d){c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+
a+". Details: "+d))})});else{var g=[],h=a;e.utils.isArray(a)||(h=[a]);for(var l=0;l<h.length;l++)g.push(b.getSync(h[l]));return g=e.utils.isArray(a)?g:g[0]}};e.extract=function(a,b){var d="",e=function(a,b){var d=~b.indexOf("#")?b.split("#")[1]:"",c=d?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(d?b.split("#")[0]:c?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==e&&0==c)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);
var f=a.firstChild;if(!f)return null;for(var k=0,c=0!=c?c-1:c;f;){if(1==f.nodeType){if(f.tagName.toLowerCase()==e&&""!=d&&f.id==d||f.tagName.toLowerCase()==e&&k==c&&""==d)return f;f.tagName.toLowerCase()==e&&k++}f=f.nextSibling}},g=function(a,b){a=a.split("/");for(var d=e(b||document,a[1]),c=2;c<a.length;c++){if(null==d)return null;d=e(d,a[c])}return d},h=function(){for(var a={},b=c.document.getElementsByTagName("META")||[],d=0,e=b.length;d<e;d++){var f=b[d].name||b[d].getAttribute("property")||"";
0!==f.length&&(a[f]=b[d].content)}return a}(),k=function(a){var b=h[a];if(b)return b;for(var b=c.document.getElementsByTagName("META")||[],d=0,e=b.length;d<e;d++){var f=b[d].name||b[d].getAttribute("property")||"";if(a==f)return b[d].content}},r=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(c.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},u=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(c.document.cookie))?val[0].split("=")[1].split(";")[0]:""},l=function(a){(a=
m(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},m=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=g(a);else try{b=eval(a)}catch(d){b=""}return b};try{return b?"meta"==b?d=k(a):"cookie"==b?d=u(a):"param"==b?d=r(a):"content"==b?d=l(a):"event"==b?d=m(a):"var"==b&&(d=c[a]):d=k(a)||u(a)||r(a)||l(a)||m(a)||c[a]||"",d||""}catch(p){return""}};if("undefined"==typeof h)var h={exports:{}};return e}(window);
window[ensightenOptions.ns].data.defineEngine("store",function(){var c={},m=window,l=m.document,b,e,g=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};c.set=function(a,b){};c.get=function(a){};c.remove=function(a){};c.clear=function(){};try{if("localStorage"in m&&m.localStorage)b=m.localStorage,c.set=function(a,d){var c,e,f=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(g(a))for(c=0,e=a.length;c<e;c++)b.setItem(a[c],"string"===
typeof d[c]?d[c]:f.stringify(d[c]));else b.setItem(a,"string"===typeof d?d:f.stringify(d))},c.get=function(a){if(g(a)){var d={},c,e;c=0;for(e=a.length;c<e;c++)d[a[c]]=b.getItem(a[c]);return d}return b.getItem(a)},c.remove=function(a){if(g(a)){var d,c;d=0;for(c=a.length;d<c;d++)b.removeItem(a[d])}else b.removeItem(a)},c.clear=function(){b.clear()},c.all=function(){return b};else if("globalStorage"in m&&m.globalStorage)b=m.globalStorage[m.location.hostname],c.set=function(a,d){if(g(a)){var c,e;c=0;
for(e=a.length;c<e;c++)b[a[c]]=d[c]}else b[a]=d},c.get=function(a){if(g(a)){var d={},c,e;c=0;for(e=a.length;c<e;c++)d[a[c]]=b[a[c]]&&b[a[c]].value;return d}return b[a]&&b[a].value},c.remove=function(a){if(g(a)){var d,c;d=0;for(c=a.length;d<c;d++)delete b[a[d]]}else delete b[a]},c.clear=function(){for(var a in b)delete b[a]},c.all=function(){return b};else if(l.documentElement.addBehavior){var h=function(a){return a.replace(n,"___")},m=function(d){return function(){var c=Array.prototype.slice.call(arguments,
0);c.unshift(b);a.appendChild(b);b.addBehavior("#default#userData");b.load("localStorage");c=d.apply(store,c);a.removeChild(b);return c}},a,f;try{f=new ActiveXObject("htmlfile"),f.open(),f.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>'),f.close(),a=f.w.frames[0].document,b=a.createElement("div")}catch(d){b=l.createElement("div"),a=l.body}var n=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g");c.set=m(function(a,b,d){if(g(b)){var e,f;e=0;for(f=b.length;e<f;e++){fixedKey=
h(b[e]);if(void 0===d[e])return c.remove(fixedKey);a.setAttribute(fixedKey,d[e]);a.save("localStorage")}}else{fixedKey=h(b);if(void 0===d)return c.remove(fixedKey);a.setAttribute(fixedKey,d);a.save("localStorage")}});c.get=m(function(a,b){if(g(b)){var d={},c,e,f;e=0;for(f=b.length;e<f;e++)c=h(b[e]),d[b[e]]=a.getAttribute(c);return d}b=h(b);return a.getAttribute(b)});c.remove=m(function(a,b){if(g(b)){var d,c;d=0;for(c=b.length;d<c;d++)a.removeAttribute(h(b[d])),a.save("localStorage")}else b=h(b),a.removeAttribute(b),
a.save("localStorage")});c.clear=m(function(a){var b=a.XMLDocument.documentElement.attributes;a.load("localStorage");for(var d=0,c;c=b[d];d++)a.removeAttribute(c.name);a.save("localStorage")});c.all=m(function(a){for(var b=a.XMLDocument.documentElement.attributes,d={},c=0,e;e=b[c];++c){var f=h(e.name);d[e.name]=a.getAttribute(f)}return d})}}catch(w){}var q={};for(e in c)q[e]=c[e];q.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());q.set(a,"test");if("test"===q.get(a))return q.remove(a),
!0}catch(b){}return!1};c.utils=q;return window[ensightenOptions.ns].data.local=c}());
window[ensightenOptions.ns].data.defineEngine("cookie",function(c,m){var l=function(){return l.get.apply(l,arguments)},b=l.utils={isArray:Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(b){return Array.prototype.slice.call(b)},getKeys:Object.keys||function(b){var c=[],h="";for(h in b)b.hasOwnProperty(h)&&c.push(h);return c},escape:function(b){return String(b).replace(/[,;"\\=\s%]/g,
function(b){return encodeURIComponent(b)})},retrieve:function(b,c){return null==b?c:b},getAllCookies:function(){if(""===c.cookie)return{};for(var b=c.cookie.split("; "),g={},h=0,a=b.length;h<a;h++){var f=b[h].split("=");g[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return g},set:function(e,g,h){h=h||-1;if(b.isPlainObject(e))for(var a in e)e.hasOwnProperty(a)&&l.set(a,e[a],g);else if(b.isArray(e)){var f;a=0;for(f=e.length;a<f;a++)l.set(e[a],g[a],h)}else{a=h.expires!==m?h.expires:l.defaults.expires||
"";"number"===typeof a&&(a=new Date(a));a=b.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():b.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;f=(f=h.path||l.defaults.path)?";path="+f:"";var d=h.domain||l.defaults.domain,d=d?";domain="+d:"";h=h.secure||l.defaults.secure?";secure":"";c.cookie=b.escape(e)+"="+b.escape(g)+a+f+d+h}},get:function(c,g){g=g||m;var h=b.getAllCookies();if(b.isArray(c)){for(var a={},f=0,d=c.length;f<d;f++)a[c[f]]=b.retrieve(h[c[f]],
g),a[c[f]]===m&&(a[c[f]]=null);return a}a=b.retrieve(h[c],g);return a===m?null:a},getGMTString:function(b){var c=new Date;c.setTime(c.getTime()+864E5*b);return c.toGMTString()}};l.defaults={path:"/",expires:b.getGMTString(90)};l.set=function(c,g){b.set(c,g)};l.remove=function(c){c=b.isArray(c)?c:b.toArray(arguments);for(var g=0,h=c.length;g<h;g++)b.set(c[g],"",{expires:-1})};l.clear=function(){return l.remove(b.getKeys(b.getAllCookies()))};l.get=function(c,g){return b.get(c,g)};l.all=function(){return b.getAllCookies()};
l.utils=b;return window[ensightenOptions.ns].data.cookie=l}(document));
}
		Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var filterMeta=function(meta){var result=[];for(var i=0;meta[i];++i)if(meta[i].name)result.push(meta[i]);return result};var getMeta=function(){var meta=filterMeta(document.getElementsByTagName("meta")||[]),n=meta.length,data={};var mapping={"WT.cg_n":"product_name","WT.site_id":"site_id","WT.site_id_name":"site_id_name","WT.registrant_id":"user_id"};var translate=function(name){return mapping[name]||
name};var name;if(!meta.length){if(!Bootstrapper.hasDOMParsed())setTimeout(getMeta,10)}else{while(n--){name=translate(meta[n].name);if(!name)continue;if(data[name]){if(typeof data[name]==="string")data[name]=[data[name]];data[name].push(meta[n].content)}else data[name]=meta[n].content||""}window._pageMetaData=data}};getMeta()},744691,299683);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=
path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId;i>0;i--)if(!~p[i].indexOf("#")&&!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);
var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};Bootstrapper.MVT=function(){var g=
{},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),i.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=
a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],getTimeout:function(){return 5},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){if(h.tests.length)this.start(h.tests)},push:function(o){if(typeof o=="object"){h.tests.push(o);Bootstrapper.MVT.hidden.push(o)}},injectCSS:function(x){var s,
d=document;if("\v"=="v"){s=d.createStyleSheet();s.cssText=x}else{s=d.createElement("style");s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);try{f.oldStyle=
f.style.display,f.style.display="none",b.style.display=b.oldStyle}catch(g){}b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);Bootstrapper.hasDOMParsed()||setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper._getServerComponent=Bootstrapper.getServerComponent;Bootstrapper.getServerComponent=function(){Bootstrapper.MVT.init();Bootstrapper._getServerComponent.apply(Bootstrapper,
arguments)};Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){var d=0;if(b.p=="replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode===
null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p=="after")if(a.parentNode==null)if(a.nextSibling!==null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}a.style.display=a.oldStyle}});Bootstrapper.MVT._traverse=
Bootstrapper.MVT.traverse;Bootstrapper.MVT.traverse=function(b,a,c){if(document.body&&typeof WTOptimize!="undefined"&&c.length>1)for(i=0;i<c.length;i++)if(c[i].t=="wt"){Bootstrapper.MVT.swap(b,c[i]);c.splice(i,1)}Bootstrapper.MVT._traverse(b,a,c)};Bootstrapper.MVT.addModule("wt",{init:function(a){if(typeof Bootstrapper.MVT.capi=="undefined"){document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+a.base+'"\x3e\x3c/sc'+"ript\x3e");Bootstrapper.MVT.capi=1}},swap:function(a,b){if(typeof WTOptimize==
"undefined")setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);else{b.o=b.o||{};b.p=b.p||{};var dbg=~window.location.href.indexOf("ensightenDebug")?true:false,isE=function(o){for(i in o)return false;return true},ta=typeof b.a!="undefined"&&b.a!=""?'"'+b.a+'",':"",pobj="",n=navigator.userAgent||navigator.vendor||window.opera,p=!!n.match(/MSIE 6|MSIE 7|MSIE 8/i)?2E3:0;Bootstrapper.MVT.wtime=Bootstrapper.MVT.wtime||4E3+p;if(dbg)console.log("swap: "+(b.a||"testAlias undefined"));if(typeof Bootstrapper.MVT.wtdone==
"undefined"){Bootstrapper.MVT.isMobile=function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4)))return true;else return false}(n);if(dbg){Bootstrapper.time=(new Date).getTime();console.log("* WTO initiated : "+Bootstrapper.time)}var addHandler=function(e){WTOptimize.addEventHandler(WTEvent[e],function(event){document.body.style.display="block";if(dbg){var time=(new Date).getTime();console.log("* WTO "+e+" : "+time+" | elapsed:"+(parseInt(time)-parseInt(Bootstrapper.time)));Bootstrapper.time=time}})},onE=["DONE","INVALID","ABORT"];for(i=0;i<onE.length;i++)addHandler(onE[i]);Bootstrapper.MVT.wtime=
Bootstrapper.MVT.isMobile?2E4:typeof b.o["s_pageTimeout"]!="undefined"?b.o["s_pageTimeout"]:Bootstrapper.MVT.wtime;setTimeout(function(){document.body.style.display="block"},Bootstrapper.MVT.wtime);Bootstrapper.MVT.wtdone=1}if(!isE(b.p))b.o["data"]=b.p;b.o["s_pageTimeout"]=Bootstrapper.MVT.wtime;b.o["s_pageDisplayMode"]="none";b.o["s_pageMode"]="head";if(dbg){for(i in b.o)if(typeof b.o[i]=="object"){pobj+=","+i+":{";for(j in b.o[i])pobj+=',"'+j+'":"'+b.o[i][j]+'"';pobj+="}"}else pobj+=","+i+':"'+
b.o[i]+'"';pobj=pobj.replace(/\{\,/g,"{");console.log(("* WTOptimize.setup("+ta+"{"+(pobj!=""?pobj:"")+"});").replace(/\{\,/g,"{")+" # "+(new Date).getTime())}eval("WTOptimize.setup("+ta+"b.o)")}}});Bootstrapper.MVT.WTOconversion=function(b){b.o=b.o||{};b.p=b.p||{};var dbg=~window.location.href.indexOf("ensightenDebug")?true:false,isE=function(o){for(i in o)return false;return true},ta=typeof b.a!="undefined"&&b.a!=""?'"'+b.a+'",':"",pobj="";if(typeof Bootstrapper.MVT.capi=="undefined"){var s=document.createElement("script");
s.type="text/javascript";s.src=b.base;document.getElementsByTagName("head")[0].appendChild(s);Bootstrapper.MVT.capi=1}if(typeof WTOptimize=="undefined")setTimeout(function(){Bootstrapper.MVT.WTOconversion(b)},10);else{if(!isE(b.p))b.o["data"]=b.p;b.o["conversionPoint"]="header";b.o["beacon"]=true;b.o["cookieInspection"]=false;WTOptimize.addEventHandler(WTEvent["PAGEVIEW"],function(event){Bootstrapper.MVT.wtPageView=1;if(dbg){for(i in b.o)if(typeof b.o[i]=="object"){pobj+=","+i+":{";for(j in b.o[i])pobj+=
',"'+j+'":"'+b.o[i][j]+'"';pobj+="}"}else pobj+=","+i+':"'+b.o[i]+'"';pobj=pobj.replace(/\{\,/g,"{");console.log(("* WTOptimize.conversion("+ta+"{"+(pobj!=""?pobj:"")+"});").replace(/\{\,/g,"{")+" # "+(new Date).getTime())}eval("WTOptimize.conversion("+ta+"b.o)")});if(typeof Bootstrapper.MVT.wtConversion=="undefined"){Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){if(typeof Bootstrapper.MVT.wtPageView=="undefined"){var c=function(){for(i in WTOptimize)if(typeof WTOptimize[i]["s_eventHandlers"]!=
"undefined")return i;return""}();try{var px=WTOptimize[c].s_eventHandlers.pageview.success;for(i=0,l=px.length;i<l;i++)px[i].call(window)}catch(e){if(dbg)console.log("* WTOptimize Conversion Error *")}}},250)});Bootstrapper.MVT.wtConversion=1}}};Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=this.deploymentId},191299,155833);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.myLog=function(a){if(window.console)console.log(a)};Bootstrapper.Cookies=new function(){var hosts=[".nature.com",".scientificamerican.com"];for(var i=0;i<hosts.length;i++){var tempRegex=new RegExp(hosts[i]);if(document.location.host.match(tempRegex))this.defaultDomain=hosts[i]}this._cookies={};this.build=function(){for(var c=document.cookie.split("; "),a=0;a<
c.length;a++)this._cookies[c[a].slice(0,c[a].indexOf("\x3d"))]=c[a].slice(c[a].indexOf("\x3d")+1)};this.get=function(c,a,f){this.build();var g=this._cookies[c];if(arguments.length==1)return g;else for(var g=g.split(f||"\x26"),d=0,b=g.length;d<b;d++)if(g[d].indexOf(a+"\x3d")==0)return g[d].slice((a+"\x3d").length,g[d].length)};this.modCookie=function(c,a,f,g){document.cookie=c+"\x3d"+a+(f?";expires\x3d"+f:"")+";domain\x3d"+(g?g:this.defaultDomain)+";path\x3d/"};this.set=function(c,a,f,g){if(arguments.length==
4){for(var d="",b=0;b<a.length;b++)d+=(b!=0?f:"")+a[b].join("\x3d");this.modCookie(c,d,g)}else if(arguments.length==3)if(typeof a=="object")if(typeof f=="object"){d="";for(b=0;b<a.length;b++)d+=(b!=0?"\x26":"")+a[b].join("\x3d");this.modCookie(c,d,f)}else{d="";for(b=0;b<a.length;b++)d+=(b!=0?f:"")+a[b].join("\x3d");this.modCookie(c,d)}else this.modCookie(c,a,f);else if(typeof a=="object"){d="";for(b=0;b<a.length;b++)d+=(b!=0?"\x26":"")+a[b].join("\x3d");this.modCookie(c,d)}else this.modCookie(c,a)};
this.addValue=function(c,a,f,g){this.build();var d=this._cookies[c]||"";if(arguments.length==4){for(var b="",e=0;e<a.length;e++)b+=(d==""&&e==0?"":f)+a[e].join("\x3d");this.modCookie(c,d+b,g)}else if(arguments.length==3)if(typeof a=="object")if(typeof f=="object"){b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":"\x26")+a[e].join("\x3d");this.modCookie(c,d+b,f)}else{b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":f)+a[e].join("\x3d");this.modCookie(c,d+b)}else this.modCookie(c,d+a,f);else if(typeof a==
"object"){b="";for(e=0;e<a.length;e++)b+=(d==""&&e==0?"":"\x26")+a[e].join("\x3d");this.modCookie(c,d+b)}else this.modCookie(c,d+a)};this.remove=function(c,a){this.build();if(this._cookies[c]){var f=(new Date).toGMTString();this.modCookie(c,"",f,a)}};this.check=function(c,a){this.build();return arguments.length==2?this.get(c).match(a+"\x3d")?!0:!1:this._cookies[c]?!0:!1};this.build()};Bootstrapper.linkTracker=function(){var _private={links:{},pushTrack:function(name,fn){if(typeof name!="string")return false;
this.links[name]=this.links[name]||[];if(typeof fn=="function")this.links[name].push(fn);return true},callTrack:function(name){if(typeof name!="string")return false;var l=_private.links[name];if(typeof l=="object"&&l.length)for(var i=0;i<l.length;i++)l[i].call(this)},debug:function(name,ref){if(window.location.search.match(/debugger=true/)){console.log("::linkTracker - Name:"+name);console.log("::linkTracker - Scope:"+ref)}}},_public={addLink:function(name,fn){return _private.pushTrack(name,fn)},
addTracking:function(name,fn){return _private.pushTrack(name,fn)},getLink:function(name){return _private.links[name]},track:function(name,ref){var $this=ref||window;_private.debug(name,$this);return _private.callTrack.call($this,name)}};return _public}();Bootstrapper.ajaxListener=function(){var listeners={},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n==
"object")if(typeof n.length!="undefined"){for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},
500);return _public}();Bootstrapper.getElementsByClassName=function(){var root=document,className="",partial=false;for(var i=0;i<arguments.length;i++)if(typeof arguments[i]=="object")root=arguments[i];else if(typeof arguments[i]=="string")className=arguments[i];else partial=arguments[i];var elements=root.getElementsByTagName("*");var retElements=[],needle=partial?new RegExp(className):new RegExp("^"+className+"$");for(var i=0;i<elements.length;i++){var tempClass=(elements[i].className||"").split(" ");
for(var j=0;j<tempClass.length;j++)if(tempClass[j].match(needle))retElements.push(elements[i])}return retElements}},151770,136502);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(){window._log=window._log||function(){};var b=Bootstrapper,d=b.data;if(d){d.calculated={data:{},top:function(g,c){var c=c||":",a=[],s=[],r=[],b;if(g&&~g.indexOf(c)){b=Bootstrapper.data.calculated.all||{};for(i in b)~i.indexOf(g)&&(a[i.split(c)[1].replace(/\_/g," ")]=b[i])}else{b=d.calculated.get(g).split(",");for(i=0;i<b.length;++i){if(!a[b[i]])a[b[i]]=0;++a[b[i]]}}for(i in a)s.push([i,
a[i]]);s.sort(function(a,b){return b[1]-a[1]});for(var i=0,l=s.length;i<l;i++)if(s[i][0]&&s[i][0]!="")r.push(s[i][0]);return r.join(",")},max:function(g,c){return d.calculated.top(g,c).split(",")[0]},rec:function(g,c,b){b="number"==typeof b?b:10;var t=d.calculated,a=t.get,e=t.set,a=a(g)||0;if(0==a)return e(g,c),c;a=a.split(",");a.length==b&&a.shift();a.push(c);a=a.join(",");return e(g,a),a},avg:function(a,e){a=a.split(e||",")||"";if(""!=a&&"object"==typeof a){if(1<a.length){var d=a.length,b=0,c;for(i=
0;i<d;i++)c=parseInt("."==a[i].charAt(0)?"0"+a[i]:a[i]),"number"==typeof c&&(b+=c);return Math.round(b/d)}return a.join("")}return""}};d.calculateData=function(n,fn){var $$LS=d.local;if($$LS&&$$LS.utils){var c=d.calculated,$$LS=$$LS.utils,$all=$$LS.all(),$name=n,$get=$$LS.get,$set=function(a,b){$$LS.set(a,b);if(a.charAt(0)!="_"){d.calculated.data[a.replace("data.","")]=b;_log("***PROFILE-UPDATED:"+a+"\x3d"+b)}},$value=$get(n)||"",$data=d.extract,$sess=$get("_data.session")||"",$session=$sess.split("-")[0],
$time=(new Date).getTime(),$url=window.location.href,$top=c.top,$max=c.max,$record=c.rec,$avg=c.avg,$first=($get("_data.firstPageOfSession")||"")=="true"?!0:!1;c.get=$get;c.set=$set;c.all=$all;if(~$sess.indexOf("-")){var ts=$sess.split("-")[1];if($time-ts>18E5){$set("_data.lastSession",$session);$sess=$time+"-"+$time;$session=$time}else $sess=$session+"-"+$time}else{$sess=$time+"-"+$time;$session=$time;$set("_data.lastSession",$session)}$set("_data.session",$sess);var $lastSession=$get("_data.lastSession")||
$session;if(n){try{$val=fn.call(window,$name,$value,$all,$get,$set,$data,$session,$lastSession,$time,$url,$top,$max,$record,$avg,$first)}catch(e){$val=$value}$val=$val==null||$val==undefined||typeof $val=="object"?"":$val;$set($name,$val);return $val}else{var C=d.calculateData;if($get("_data.visitStamp")!=$session)C("data.visit",function(n,v,a,g,s,d,e,l,t,u,p,m,r,w,f){var v=v||0,x=12,pv=g("data.sessionPageViews")||"",ts=g("data.timeOnSite")||"";s("data.landingPage",u);s("data.lastExitPage",g("_data.currPage")||
"");s("data.uuid",d("uuid","cookie")||"");r("_data.avgTime",g("data.timeOnSite")||"");r("_data.avgPageViews",g("data.sessionPageViews")||"");if(l!=""&&pv!=""&&ts!="")r("_data.engagementTrend",l+"|"+pv+"|"+ts);s("data.averageTimeOnSite",w(g("_data.avgTime"))||"");s("data.averageSessionPageViews",w(g("_data.avgPageViews"))||"");s("data.visitorType",e!=l?"Returning":"New");s("data.visitorGroup",g("data.visitorGroup")||Math.ceil(Math.random()*x));s("data.daysSinceLastVisit",e!=l?parseInt(((e-l)/(24*60*
60*1E3)).toFixed(0)):0);s("_data.visitStamp",e);return++v});C("data.sessionPageViews",function(n,v,a,g,s,d,e,l,t,u,p,m,r,w,f){var v=v||0,p=g("data.totalPageViews")||0;s("data.totalPageViews",++p);s("data.timeOnSite",((t-e)/(60*1E3)).toFixed(0));s("_data.currPage",u);if(g("_data.sessionStamp")!=e){s("_data.sessionStamp",e);s("_data.firstPageOfSession","true");return 1}else{s("_data.firstPageOfSession","false");return++v}})}}};d.calculateData()}})()},835508,290842);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.dataManager=function(){var _private={data:{},add:function(o){if(typeof o=="object"&&o.id)this.data[o.id]=o},getObj:function(i){if(i)return _private.data[i];return _private.data},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{if(typeof dataObj[key].get=="string"){var d=eval(dataObj[key].get);if(typeof dataObj[key].mod==
"string"&&dataObj[key].mod!==""){var m="(function(){ return "+(dataObj[key].mod===""?"this":dataObj[key].mod)+";})";retObj[key]=eval(m).call(d)}else if(typeof dataObj[key].mod=="function")retObj[key]=dataObj[key].mod.call(d,d);else retObj[key]=d}else if(typeof dataObj[key].get=="function"){var d=dataObj[key].get();if(typeof dataObj[key].mod=="string"&&dataObj[key].mod!==""){var m="(function(){ return "+(dataObj[key].mod===""?"this":dataObj[key].mod)+";})";retObj[key]=eval(m).call(d)}else if(typeof dataObj[key].mod==
"function")retObj[key]=dataObj[key].mod.call(d,d);else retObj[key]=d}}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o==
"object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},getObj:function(i){return _private.getObj(i)},getData:function(i){return _private.getData(i)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}()},191343,155832);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!window.location.pathname.match(/^\/(nature_education|scitable|principles)(\/|$)/))document.write('\x3cscript class\x3d"kxct" data-id\x3d"Jn7TaPwq" data-timing\x3d"async" data-version\x3d"1.9" type\x3d"text/javascript"\x3ewindow.Krux||((Krux\x3dfunction(){Krux.q.push(arguments)}).q\x3d[]);(function(){var k\x3ddocument.createElement("script");k.type\x3d"text/javascript";k.async\x3dtrue;var m,src\x3d(m\x3dlocation.href.match(/\\bkxsrc\x3d([^\x26]+)/))\x26\x26decodeURIComponent(m[1]);k.src \x3d /^https?:\\/\\/([a-z0-9_\\-\\.]+\\.)?krxd\\.net(:\\d{1,5})?\\//i.test(src) ? src : src \x3d\x3d\x3d "disable" ? "" :(location.protocol\x3d\x3d\x3d"https:"?"https:":"http:")+"//cdn.krxd.net/controltag?confid\x3dJn7TaPwq";var s\x3ddocument.getElementsByTagName("script")[0];s.parentNode.insertBefore(k,s);}());\x3c/script\x3e')},744582,
[744691],291427,[299683]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!window.location.pathname.match(/^\/(nature_education|scitable|principles)(\/|$)/))document.write("\x3cscript class\x3d'kxint' type\x3d'text/javascript'\x3ewindow.Krux || ((Krux \x3d function() {Krux.q.push(arguments);}).q \x3d []);(function() {function retrieve(n) {var m, k \x3d 'kx' + n;if (window.localStorage) {return window.localStorage[k] || '';} else if (navigator.cookieEnabled) {m \x3d document.cookie.match(k + '\x3d([^;]*)');return (m \x26\x26 unescape(m[1])) || '';} else {return '';}}Krux.user \x3d retrieve('user');Krux.segments \x3d retrieve('segs') ? retrieve('segs').split(',') : []; var dfpp \x3d [];if (Krux.user) {dfpp.push('kuid\x3d' + Krux.user);}for (var i \x3d 0; i \x3c Krux.segments.length; i++) {dfpp.push('ksg\x3d' + Krux.segments[i]);}Krux.dfppKeyValues \x3d dfpp.length ? dfpp.join(';') + ';' : '';})();\x3c/script\x3e")},830157,
306102);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var isTestPage=function(path){var patterns=[/^\/ecommerce(?:\/|$)/,/^\/news(?:\/|$)/,/^\/register(?:\/|$)/,/^\/nams\/svc\/register(?:\/|$)/,/^\/verify(?:\/|$)/];for(var i=0;patterns[i];++i)if(path.match(patterns[i]))return true;return false};if(location.hostname.match(/^(?:www|secure)\.nature\.com$/)&&isTestPage(location.pathname))document.write('\x3cscript src\x3d"//cdn.optimizely.com/js/27142879.js"\x3e\x3c/script\x3e')},791234,
259560);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.npg=Bootstrapper.npg||{};Bootstrapper.npg.utils=function(global,undefined){var params=function(){var match=null,params={},param=/([^&=]+)=?([^&]*)/g,decode=function(str){return decodeURIComponent(str.replace(/\+/g," "))},query=global.location.search.substring(1);while(match=param.exec(query))params[decode(match[1])]=decode(match[2]);return params}();var cookies=
function(){var pairs=document.cookie.split(/;\s*/),pair=null,n=pairs.length,cookies={};while(n--){pair=pairs[n].split("\x3d");cookies[pair[0]]=pair[1]}return cookies}();return{Request:{get:function(key){return arguments.length===1?params[key]||undefined:params},cookie:function(key){if(arguments.length===0)return cookies;if(arguments.length===1)return cookies[key]||undefined;return this.setCookie.apply(this,[].slice.call(arguments,0))},setCookie:function(name,value,opts){var params=[name+"\x3d"+value],
d=null;opts=opts||{};if(opts.days){d=new Date;d.setTime(+d+opts.days*24*60*60*1E3);params.push("expires\x3d"+d.toGMTString())}if(opts.path)params.push("path\x3d"+opts.path);if(opts.domain)params.push("domain\x3d"+opts.domain);document.cookie=params.join(";");return true}},onJqueryDefined:function(callback){var self=this;if(global.jQuery)callback(global.jQuery);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){self.onJqueryDefined(callback)},100);else callback(null)},onWebtrendsDefined:function(callback){var self=
this;var wt=window.dcs&&(!window._tag||!window._tag.dcsCollect)?window.dcs:null;if(wt&&Bootstrapper.hasDOMParsed())callback(wt);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){self.onWebtrendsDefined(callback)},100);else callback(null)}}}(window)},484780,136555);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();